
sudo: required

language: cpp

services:
    - docker

env:
    - COMPILER=gcc-5
    - COMPILER=gcc-6
    - COMPILER=gcc-7
    - COMPILER=clang-3.8
    - COMPILER=clang-3.9

before_install:
    - docker pull icepack/dealii:$COMPILER
    - docker run -itd --volume $TRAVIS_BUILD_DIR:/repo --name build icepack/dealii:$COMPILER

script:
    - docker exec build cmake -H/repo -B/build
    - docker exec build cmake --build /build
    - docker exec build cmake --build /build --target test

