
sudo: required

language: cpp

services:
    - docker

env:
    - VERSION=5
    - VERSION=6
    - VERSION=7

before_install:
    - docker pull icepack/dealii:gcc-$VERSION
    - docker run -itd --volume $TRAVIS_BUILD_DIR:/repo --name build icepack/dealii:gcc-$VERSION

script:
    - docker exec build cmake -H/repo -B/build
    - docker exec build cmake --build /build
    - docker exec build cmake --build /build --target test

